# Getting Financial Data - Google Finance

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import datetime as dt
import yfinance as yf

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is)

In [3]:
date_start = '2015-01-01'
date_end = dt.datetime.today().strftime('%Y-%m-%d')

date_end

'2026-01-26'

### Step 3. Select the Apple, Tesla, Twitter, IBM, LinkedIn stocks symbols and assign them to a variable called stocks

In [4]:
stocks = yf.download(['AAPL','NVDA','MSFT','TSLA'],date_start,date_end)
stocks

[*********************100%***********************]  4 of 4 completed

Price            Close                                            High  \
Ticker            AAPL        MSFT        NVDA        TSLA        AAPL
Date
2015-01-02   24.237551   39.858440    0.483011   14.620667   24.705320
2015-01-05   23.554747   39.491932    0.474853   14.006000   24.086807
2015-01-06   23.556957   38.912289    0.460456   14.085333   23.816336
2015-01-07   23.887272   39.406685    0.459257   14.063333   23.987032
2015-01-08   24.805080   40.565952    0.476533   14.041333   24.862721
...                ...         ...         ...         ...         ...
2026-01-16  255.529999  459.859985  186.229996  437.500000  258.899994
2026-01-20  246.699997  454.519989  178.070007  419.250000  254.789993
2026-01-21  247.649994  444.109985  183.320007  431.440002  251.559998
2026-01-22  248.350006  451.140015  184.839996  449.359985  251.000000
2026-01-23  248.039993  465.950012  187.669998  449.059998  249.410004

Price                                                  Low              \
Ticker            MSFT        NVDA        TSLA        AAPL        MSFT
Date
2015-01-02   40.421027    0.486611   14.883333   23.798600   39.670914
2015-01-05   39.832892    0.484451   14.433333   23.368526   39.423738
2015-01-06   39.849933    0.476053   14.280000   23.195599   38.818524
2015-01-07   39.602738    0.467895   14.318667   23.654495   38.775907
2015-01-08   40.702337    0.479412   14.253333   24.097883   39.824361
...                ...         ...         ...         ...         ...
2026-01-16  463.190002  190.440002  447.250000  254.929993  456.480011
2026-01-20  456.799988  182.380005  430.730011  243.419998  449.279999
2026-01-21  452.690002  185.380005  438.200012  245.179993  438.679993
2026-01-22  452.839996  186.169998  449.500000  248.149994  444.700012
2026-01-23  471.100006  189.600006  452.429993  244.679993  450.529999

Price                                     Open                          \
Ticker            NVDA        TSLA        AAPL        MSFT        NVDA
Date
2015-01-02    0.475333   14.217333   24.694235   39.773201    0.483011
2015-01-05    0.472694   13.810667   24.006998   39.526026    0.483011
2015-01-06    0.459977   13.614000   23.619031   39.534544    0.475573
2015-01-07    0.457817   13.985333   23.765341   39.193584    0.463816
2015-01-08    0.464296   14.000667   24.215381   39.849932    0.464536
...                ...         ...         ...         ...         ...
2026-01-16  186.080002  435.260010  257.899994  457.829987  189.080002
2026-01-20  177.610001  417.440002  252.729996  451.220001  181.899994
2026-01-21  178.399994  419.619995  248.699997  452.600006  179.050003
2026-01-22  183.929993  432.630005  249.199997  447.619995  184.750000
2026-01-23  186.820007  444.040009  247.320007  451.869995  187.500000

Price                      Volume
Ticker            TSLA       AAPL      MSFT       NVDA      TSLA
Date
2015-01-02   14.858000  212818400  27913900  113680000  71466000
2015-01-05   14.303333  257142000  39673900  197952000  80527500
2015-01-06   14.004000  263188400  36447900  197764000  93928500
2015-01-07   14.223333  160423600  29114100  321808000  44526000
2015-01-08   14.187333  237458000  29645200  283780000  51637500
...                ...        ...       ...        ...       ...
2026-01-16  439.500000   72142800  34246700  187967200  60220600
2026-01-20  429.359985   80267500  26130000  223345300  63187300
2026-01-21  421.660004   54641700  37980500  200381000  68124000
2026-01-22  435.160004   39708300  25349400  139636600  71546700
2026-01-23  447.429993   41625700  37962400  142524700  56636400

[2781 rows x 20 columns]

In [5]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2781 entries, 2015-01-02 to 2026-01-23
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   2781 non-null   float64
 1   (Close, MSFT)   2781 non-null   float64
 2   (Close, NVDA)   2781 non-null   float64
 3   (Close, TSLA)   2781 non-null   float64
 4   (High, AAPL)    2781 non-null   float64
 5   (High, MSFT)    2781 non-null   float64
 6   (High, NVDA)    2781 non-null   float64
 7   (High, TSLA)    2781 non-null   float64
 8   (Low, AAPL)     2781 non-null   float64
 9   (Low, MSFT)     2781 non-null   float64
 10  (Low, NVDA)     2781 non-null   float64
 11  (Low, TSLA)     2781 non-null   float64
 12  (Open, AAPL)    2781 non-null   float64
 13  (Open, MSFT)    2781 non-null   float64
 14  (Open, NVDA)    2781 non-null   float64
 15  (Open, TSLA)    2781 non-null   float64
 16  (Volume, AAPL)  2781 non-null   int64
 17  (Volume, MSFT)  2781 non-null   int64
 18  (Volume, NVDA)  2781 non-null   int64
 19  (Volume, TSLA)  2781 non-null   int64
dtypes: float64(16), int64(4)
memory usage: 456.3 KB

### Step 4. Read the data from google, assign to df and print it

In [13]:
stocks = pd.DataFrame(stocks)
stocks

Price            Close                                            High  \
Ticker            AAPL        MSFT        NVDA        TSLA        AAPL
Date
2015-01-02   24.237551   39.858440    0.483011   14.620667   24.705320
2015-01-05   23.554747   39.491932    0.474853   14.006000   24.086807
2015-01-06   23.556957   38.912289    0.460456   14.085333   23.816336
2015-01-07   23.887272   39.406685    0.459257   14.063333   23.987032
2015-01-08   24.805080   40.565952    0.476533   14.041333   24.862721
...                ...         ...         ...         ...         ...
2026-01-16  255.529999  459.859985  186.229996  437.500000  258.899994
2026-01-20  246.699997  454.519989  178.070007  419.250000  254.789993
2026-01-21  247.649994  444.109985  183.320007  431.440002  251.559998
2026-01-22  248.350006  451.140015  184.839996  449.359985  251.000000
2026-01-23  248.039993  465.950012  187.669998  449.059998  249.410004

Price                                                  Low              \
Ticker            MSFT        NVDA        TSLA        AAPL        MSFT
Date
2015-01-02   40.421027    0.486611   14.883333   23.798600   39.670914
2015-01-05   39.832892    0.484451   14.433333   23.368526   39.423738
2015-01-06   39.849933    0.476053   14.280000   23.195599   38.818524
2015-01-07   39.602738    0.467895   14.318667   23.654495   38.775907
2015-01-08   40.702337    0.479412   14.253333   24.097883   39.824361
...                ...         ...         ...         ...         ...
2026-01-16  463.190002  190.440002  447.250000  254.929993  456.480011
2026-01-20  456.799988  182.380005  430.730011  243.419998  449.279999
2026-01-21  452.690002  185.380005  438.200012  245.179993  438.679993
2026-01-22  452.839996  186.169998  449.500000  248.149994  444.700012
2026-01-23  471.100006  189.600006  452.429993  244.679993  450.529999

Price                                     Open                          \
Ticker            NVDA        TSLA        AAPL        MSFT        NVDA
Date
2015-01-02    0.475333   14.217333   24.694235   39.773201    0.483011
2015-01-05    0.472694   13.810667   24.006998   39.526026    0.483011
2015-01-06    0.459977   13.614000   23.619031   39.534544    0.475573
2015-01-07    0.457817   13.985333   23.765341   39.193584    0.463816
2015-01-08    0.464296   14.000667   24.215381   39.849932    0.464536
...                ...         ...         ...         ...         ...
2026-01-16  186.080002  435.260010  257.899994  457.829987  189.080002
2026-01-20  177.610001  417.440002  252.729996  451.220001  181.899994
2026-01-21  178.399994  419.619995  248.699997  452.600006  179.050003
2026-01-22  183.929993  432.630005  249.199997  447.619995  184.750000
2026-01-23  186.820007  444.040009  247.320007  451.869995  187.500000

Price                      Volume
Ticker            TSLA       AAPL      MSFT       NVDA      TSLA
Date
2015-01-02   14.858000  212818400  27913900  113680000  71466000
2015-01-05   14.303333  257142000  39673900  197952000  80527500
2015-01-06   14.004000  263188400  36447900  197764000  93928500
2015-01-07   14.223333  160423600  29114100  321808000  44526000
2015-01-08   14.187333  237458000  29645200  283780000  51637500
...                ...        ...       ...        ...       ...
2026-01-16  439.500000   72142800  34246700  187967200  60220600
2026-01-20  429.359985   80267500  26130000  223345300  63187300
2026-01-21  421.660004   54641700  37980500  200381000  68124000
2026-01-22  435.160004   39708300  25349400  139636600  71546700
2026-01-23  447.429993   41625700  37962400  142524700  56636400

[2781 rows x 20 columns]

### Step 5.  What is the type of structure of df ?

In [ ]:
# a panel data structure?

### Step 6. Print all the Items axis values
#### To learn more about the Panel structure go to [documentation](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#panel)

In [14]:
print(stocks.axes)

[DatetimeIndex(['2015-01-02', '2015-01-05', '2015-01-06', '2015-01-07',
               '2015-01-08', '2015-01-09', '2015-01-12', '2015-01-13',
               '2015-01-14', '2015-01-15',
               ...
               '2026-01-09', '2026-01-12', '2026-01-13', '2026-01-14',
               '2026-01-15', '2026-01-16', '2026-01-20', '2026-01-21',
               '2026-01-22', '2026-01-23'],
              dtype='datetime64[ns]', name='Date', length=2781, freq=None), MultiIndex([( 'Close', 'AAPL'),
            ( 'Close', 'MSFT'),
            ( 'Close', 'NVDA'),
            ( 'Close', 'TSLA'),
            (  'High', 'AAPL'),
            (  'High', 'MSFT'),
            (  'High', 'NVDA'),
            (  'High', 'TSLA'),
            (   'Low', 'AAPL'),
            (   'Low', 'MSFT'),
            (   'Low', 'NVDA'),
            (   'Low', 'TSLA'),
            (  'Open', 'AAPL'),
            (  'Open', 'MSFT'),
            (  'Open', 'NVDA'),
            (  'Open', 'TSLA'),
            ('Volume', 'AAPL'),
            ('Volume', 'MSFT'),
            ('Volume', 'NVDA'),
            ('Volume', 'TSLA')],
           names=['Price', 'Ticker'])]

### Step 7. Good, now we know  the data avaiable. Create a dataFrame called vol, with the Volume values.

In [10]:
vol = stocks['Volume']
vol.head()

Ticker           AAPL      MSFT       NVDA      TSLA
Date
2015-01-02  212818400  27913900  113680000  71466000
2015-01-05  257142000  39673900  197952000  80527500
2015-01-06  263188400  36447900  197764000  93928500
2015-01-07  160423600  29114100  321808000  44526000
2015-01-08  237458000  29645200  283780000  51637500

### Step 8. Aggregate the data of Volume to weekly
#### Hint: Be careful to not sum data from the same week of 2015 and other years.

In [11]:
vol_weekly = vol.resample('W').sum()
vol_weekly.head()

Ticker            AAPL       MSFT        NVDA       TSLA
Date
2015-01-04   212818400   27913900   113680000   71466000
2015-01-11  1133010000  158825300  1210844000  340644000
2015-01-18  1216906400  157088200   953156000  461988000
2015-01-25   794948000  137352600   565216000  243175500
2015-02-01  1863370800  437786800  1297456000  235803000

### Step 9. Find all the volume traded in the year of 2015

In [18]:
vol_2015 = vol.groupby(vol.index.year).get_group(2015).sum()
vol_2015

Ticker
AAPL    52264199600
MSFT     9059455900
NVDA    78187564000
TSLA    16323267000
dtype: int64

### BONUS: Create your own question and answer it.