In [21]:
import pandas as pd

## Indexing & selection (loc vs iloc)

In [18]:
data = pd.read_csv(r"D:\2-zindua\03-python-data-analysis\zindua-python-data-analysis\wk2_pandas\mobile_sales.csv")

data.head()

,TransactionID,Date,MobileModel,Brand,Price,UnitsSold,TotalRevenue,CustomerAge,CustomerGender,Location,PaymentMethod
0,79397f68-61ed-4ea8-bcb2-f918d4e6c05b,2024-01-06,direction,Green Inc,1196.95,85,28002.80,32,Female,Port Erik,Online
1,4f87d114-f522-4ead-93e3-f336402df6aa,2024-04-05,right,Thomas-Thompson,1010.34,64,2378.82,55,Female,East Linda,Credit Card
2,6750b7d6-dcc5-48c5-a76a-b6fc9d540fe1,2024-02-13,summer,Sanchez-Williams,400.80,95,31322.56,57,Male,East Angelicastad,Online
3,7da7de95-f772-4cc2-bce0-b0873f98233e,2024-04-17,keep,Greer and Sons,338.60,79,31159.75,46,Other,East Kevin,Cash
4,469044af-0d60-4d87-af66-c6603e844057,2024-06-02,option,Brown and Sons,839.79,41,11523.36,38,Male,New Lindaborough,Online

In [19]:
# print index column

data.index

RangeIndex(start=0, stop=1000, step=1)

In [23]:
# iloc -> index locator
# df[row_index, column_index]

data.iloc[1,:]

TransactionID     4f87d114-f522-4ead-93e3-f336402df6aa
Date                                        2024-04-05
MobileModel                                      right
Brand                                  Thomas-Thompson
Price                                          1010.34
UnitsSold                                           64
TotalRevenue                                   2378.82
CustomerAge                                         55
CustomerGender                                  Female
Location                                    East Linda
PaymentMethod                              Credit Card
Name: 1, dtype: object

In [28]:
# ranges

data.iloc[2:5,3:8]

              Brand   Price  UnitsSold  TotalRevenue  CustomerAge
2  Sanchez-Williams  400.80         95      31322.56           57
3    Greer and Sons  338.60         79      31159.75           46
4    Brown and Sons  839.79         41      11523.36           38

In [29]:
data.iloc[2:,3:]

,Brand,Price,UnitsSold,TotalRevenue,CustomerAge,CustomerGender,Location,PaymentMethod
2,Sanchez-Williams,400.80,95,31322.56,57,Male,East Angelicastad,Online
3,Greer and Sons,338.60,79,31159.75,46,Other,East Kevin,Cash
4,Brown and Sons,839.79,41,11523.36,38,Male,New Lindaborough,Online
5,"Massey, Nicholson and Young",1498.13,70,9703.89,45,Female,Port Daryl,Debit Card
6,Coleman-Pena,975.77,63,8300.22,23,Other,Kathrynborough,Online
...,...,...,...,...,...,...,...,...
995,Brooks Ltd,1386.69,76,28865.70,39,Male,Ronaldchester,Credit Card
996,"Lang, Brown and Stone",1159.26,59,50471.42,21,Other,West Jenniferport,Credit Card
997,"Atkinson, Moore and Nelson",544.31,59,1381.82,26,Female,Barneschester,Credit Card
998,"Kim, Maxwell and Moore",331.98,84,8557.32,20,Male,Jonesborough,Online
999,Wallace LLC,973.97,79,70739.76,44,Female,Port Luis,Credit Card

In [31]:
# loc -> uses row and column labels (not indices)

data.head()

,TransactionID,Date,MobileModel,Brand,Price,UnitsSold,TotalRevenue,CustomerAge,CustomerGender,Location,PaymentMethod
0,79397f68-61ed-4ea8-bcb2-f918d4e6c05b,2024-01-06,direction,Green Inc,1196.95,85,28002.80,32,Female,Port Erik,Online
1,4f87d114-f522-4ead-93e3-f336402df6aa,2024-04-05,right,Thomas-Thompson,1010.34,64,2378.82,55,Female,East Linda,Credit Card
2,6750b7d6-dcc5-48c5-a76a-b6fc9d540fe1,2024-02-13,summer,Sanchez-Williams,400.80,95,31322.56,57,Male,East Angelicastad,Online
3,7da7de95-f772-4cc2-bce0-b0873f98233e,2024-04-17,keep,Greer and Sons,338.60,79,31159.75,46,Other,East Kevin,Cash
4,469044af-0d60-4d87-af66-c6603e844057,2024-06-02,option,Brown and Sons,839.79,41,11523.36,38,Male,New Lindaborough,Online

In [32]:
data.loc[0,:]

TransactionID     79397f68-61ed-4ea8-bcb2-f918d4e6c05b
Date                                        2024-01-06
MobileModel                                  direction
Brand                                        Green Inc
Price                                          1196.95
UnitsSold                                           85
TotalRevenue                                   28002.8
CustomerAge                                         32
CustomerGender                                  Female
Location                                     Port Erik
PaymentMethod                                   Online
Name: 0, dtype: object

In [33]:
data.loc[0:2, 'Date']

0    2024-01-06
1    2024-04-05
2    2024-02-13
Name: Date, dtype: object

In [35]:
data.columns

Index(['TransactionID', 'Date', 'MobileModel', 'Brand', 'Price', 'UnitsSold',
       'TotalRevenue', 'CustomerAge', 'CustomerGender', 'Location',
       'PaymentMethod'],
      dtype='object')

In [34]:
data.loc[0:2, 'Date':'CustomerAge']

,Date,MobileModel,Brand,Price,UnitsSold,TotalRevenue,CustomerAge
0,2024-01-06,direction,Green Inc,1196.95,85,28002.80,32
1,2024-04-05,right,Thomas-Thompson,1010.34,64,2378.82,55
2,2024-02-13,summer,Sanchez-Williams,400.80,95,31322.56,57

## Hierarchical Indexing/Multiindex
Useful when using an index on a single column is not sufficient to retreive the intended data e.g. moving from sales by country to sales by country, then by city, then by year(multiple dimensions)
- simplified idea: an index within an index

In [36]:
# without hierarchical indexing

data = {
    "country": ["Kenya", "Kenya", "Uganda", "Uganda"],
    "city": ["Nairobi", "Mombasa", "Kampala", "Gulu"],
    "sales": [100, 80, 90, 40]
}

pd.DataFrame(data)

# country and city are regular columns, so some values are repeated

  country     city  sales
0   Kenya  Nairobi    100
1   Kenya  Mombasa     80
2  Uganda  Kampala     90
3  Uganda     Gulu     40

In [37]:
# with hierarchical indexing

countries_n_cities = [
    ["Kenya", "Kenya", "Uganda", "Uganda"],
    ["Nairobi", "Mombasa", "Kampala", "Gulu"]
]

index = pd.MultiIndex.from_arrays(countries_n_cities, names=("country", "city"))

pd.DataFrame(
    {"sales": [100, 80, 90, 40]},
    index=index
)

# now there are 2 levels of the row index: country and city, where country groups multiple cities

# similar to merging cells in excel to show shared values?
# similar to using compound keys in sql

# q: is eliminating repetition that efficient?

                 sales
country city
Kenya   Nairobi    100
        Mombasa     80
Uganda  Kampala     90
        Gulu        40

In [ ]:
index = pd.MultiIndex.from_arrays(countries_n_cities, names=("country", "city"))

# index -> a variable containing the multiindex created
# pd.MultiIndex.from_arrays -> method to create a multiindex from an array (list of lists)
# names -> column headers for each of the indices

In [38]:
index

MultiIndex([( 'Kenya', 'Nairobi'),
            ( 'Kenya', 'Mombasa'),
            ('Uganda', 'Kampala'),
            ('Uganda',    'Gulu')],
           names=['country', 'city'])

In [39]:
help(pd.MultiIndex)

# params and method definitions

Help on class MultiIndex in module pandas.core.indexes.multi:

class MultiIndex(pandas.core.indexes.base.Index)
 |  MultiIndex(
 |      levels=None,
 |      codes=None,
 |      sortorder=None,
 |      names=None,
 |      dtype=None,
 |      copy: bool = False,
 |      name=None,
 |      verify_integrity: bool = True
 |  ) -> Self
 |
 |  A multi-level, or hierarchical, index object for pandas objects.
 |
 |  Parameters
 |  ----------
 |  levels : sequence of arrays
 |      The unique labels for each level.
 |  codes : sequence of arrays
 |      Integers for each level designating which label at each location.
 |  sortorder : optional int
 |      Level of sortedness (must be lexicographically sorted by that
 |      level).
 |  names : optional sequence of objects
 |      Names for each of the index levels. (name is accepted for compat).
 |  copy : bool, default False
 |      Copy the meta-data.
 |  verify_integrity : bool, default True
 |      Check that the levels/codes are consistent and valid.
 |
 |  Attributes
 |  ----------
 |  names
 |  levels
 |  codes
 |  nlevels
 |  levshape
 |  dtypes
 |
 |  Methods
 |  -------
 |  from_arrays
 |  from_tuples
 |  from_product
 |  from_frame
 |  set_levels
 |  set_codes
 |  to_frame
 |  to_flat_index
 |  sortlevel
 |  droplevel
 |  swaplevel
 |  reorder_levels
 |  remove_unused_levels
 |  get_level_values
 |  get_indexer
 |  get_loc
 |  get_locs
 |  get_loc_level
 |  drop
 |
 |  See Also
 |  --------
 |  MultiIndex.from_arrays  : Convert list of arrays to MultiIndex.
 |  MultiIndex.from_product : Create a MultiIndex from the cartesian product
 |                            of iterables.
 |  MultiIndex.from_tuples  : Convert list of tuples to a MultiIndex.
 |  MultiIndex.from_frame   : Make a MultiIndex from a DataFrame.
 |  Index : The base pandas Index type.
 |
 |  Notes
 |  -----
 |  See the `user guide
 |  <https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html>`__
 |  for more.
 |
 |  Examples
 |  --------
 |  A new ``MultiIndex`` is typically constructed using one of the helper
 |  methods :meth:`MultiIndex.from_arrays`, :meth:`MultiIndex.from_product`
 |  and :meth:`MultiIndex.from_tuples`. For example (using ``.from_arrays``):
 |
 |  >>> arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]
 |  >>> pd.MultiIndex.from_arrays(arrays, names=('number', 'color'))
 |  MultiIndex([(1,  'red'),
 |              (1, 'blue'),
 |              (2,  'red'),
 |              (2, 'blue')],
 |             names=['number', 'color'])
 |
 |  See further examples for how to construct a MultiIndex in the doc strings
 |  of the mentioned helper methods.
 |
 |  Method resolution order:
 |      MultiIndex
 |      pandas.core.indexes.base.Index
 |      pandas.core.base.IndexOpsMixin
 |      pandas.core.arraylike.OpsMixin
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __abs__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __add__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __array__(self, dtype=None, copy=None) -> np.ndarray
 |      the array interface, return my values
 |
 |  __contains__(self, key: Any) -> bool
 |      Return a boolean indicating whether the provided key is in the index.
 |
 |      Parameters
 |      ----------
 |      key : label
 |          The key to check if it is present in the index.
 |
 |      Returns
 |      -------
 |      bool
 |          Whether the key search is in the index.
 |
 |      Raises
 |      ------
 |      TypeError
 |          If the key is not hashable.
 |
 |      See Also
 |      --------
 |      Index.isin : Returns an ndarray of boolean dtype indicating whether the
 |          list-like key is in the index.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index([1, 2, 3, 4])
 |      >>> idx
 |      Index([1, 2, 3, 4], dtype='int64')
 |
 |      >>> 2 in idx
 |      True
 |      >>> 6 in idx
 |      False
 |
 |  __divmod__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __floordiv__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __getitem__(self, key)
 |      Override numpy.ndarray's __getitem__ method to work as desired.
 |
 |      This function adds lists and Series as valid boolean indexers
 |      (ndarrays only supports ndarray with dtype=bool).
 |
 |      If resulting ndim != 1, plain ndarray is returned instead of
 |      corresponding `Index` subclass.
 |
 |  __iadd__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __invert__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __isub__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __len__(self) -> int
 |      Return the length of the Index.
 |
 |  __mod__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __mul__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __neg__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __pos__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __pow__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __radd__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __rdivmod__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __reduce__(self)
 |      Necessary for making this object picklable
 |
 |  __rfloordiv__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __rmod__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __rmul__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __rpow__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __rsub__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __rtruediv__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __sub__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  __truediv__(self, other=None) from pandas.core.ops.invalid.make_invalid_op.<locals>
 |
 |  append(self, other)
 |      Append a collection of Index options together.
 |
 |      Parameters
 |      ----------
 |      other : Index or list/tuple of indices
 |
 |      Returns
 |      -------
 |      Index
 |          The combined index.
 |
 |      Examples
 |      --------
 |      >>> mi = pd.MultiIndex.from_arrays([['a'], ['b']])
 |      >>> mi
 |      MultiIndex([('a', 'b')],
 |                 )
 |      >>> mi.append(mi)
 |      MultiIndex([('a', 'b'), ('a', 'b')],
 |                 )
 |
 |  argsort(self, *args, na_position: str = 'last', **kwargs) -> npt.NDArray[np.intp]
 |      Return the integer indices that would sort the index.
 |
 |      Parameters
 |      ----------
 |      *args
 |          Passed to `numpy.ndarray.argsort`.
 |      **kwargs
 |          Passed to `numpy.ndarray.argsort`.
 |
 |      Returns
 |      -------
 |      np.ndarray[np.intp]
 |          Integer indices that would sort the index if used as
 |          an indexer.
 |
 |      See Also
 |      --------
 |      numpy.argsort : Similar method for NumPy arrays.
 |      Index.sort_values : Return sorted copy of Index.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index(['b', 'a', 'd', 'c'])
 |      >>> idx
 |      Index(['b', 'a', 'd', 'c'], dtype='object')
 |
 |      >>> order = idx.argsort()
 |      >>> order
 |      array([1, 0, 3, 2])
 |
 |      >>> idx[order]
 |      Index(['a', 'b', 'c', 'd'], dtype='object')
 |
 |  astype(self, dtype, copy: bool = True)
 |      Create an Index with values cast to dtypes.
 |
 |      The class of a new Index is determined by dtype. When conversion is
 |      impossible, a TypeError exception is raised.
 |
 |      Parameters
 |      ----------
 |      dtype : numpy dtype or pandas type
 |          Note that any signed integer `dtype` is treated as ``'int64'``,
 |          and any unsigned integer `dtype` is treated as ``'uint64'``,
 |          regardless of the size.
 |      copy : bool, default True
 |          By default, astype always returns a newly allocated object.
 |          If copy is set to False and internal requirements on dtype are
 |          satisfied, the original data is used to create a new Index
 |          or the original Index is returned.
 |
 |      Returns
 |      -------
 |      Index
 |          Index with values cast to specified dtype.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index([1, 2, 3])
 |      >>> idx
 |      Index([1, 2, 3], dtype='int64')
 |      >>> idx.astype('float')
 |      Index([1.0, 2.0, 3.0], dtype='float64')
 |
 |  copy(self, names=None, deep: bool = False, name=None) -> Self
 |      Make a copy of this object.
 |
 |      Names, dtype, levels and codes can be passed and will be set on new copy.
 |
 |      Parameters
 |      ----------
 |      names : sequence, optional
 |      deep : bool, default False
 |      name : Label
 |          Kept for compatibility with 1-dimensional Index. Should not be used.
 |
 |      Returns
 |      -------
 |      MultiIndex
 |
 |      Notes
 |      -----
 |      In most cases, there should be no functional difference from using
 |      ``deep``, but if ``deep`` is passed it will attempt to deepcopy.
 |      This could be potentially expensive on large MultiIndex objects.
 |
 |      Examples
 |      --------
 |      >>> mi = pd.MultiIndex.from_arrays([['a'], ['b'], ['c']])
 |      >>> mi
 |      MultiIndex([('a', 'b', 'c')],
 |                 )
 |      >>> mi.copy()
 |      MultiIndex([('a', 'b', 'c')],
 |                 )
 |
 |  delete(self, loc) -> MultiIndex
 |      Make new index with passed location deleted
 |
 |      Returns
 |      -------
 |      new_index : MultiIndex
 |
 |  drop(
 |      self,
 |      codes,
 |      level: Index | np.ndarray | Iterable[Hashable] | None = None,
 |      errors: IgnoreRaise = 'raise'
 |  ) -> MultiIndex
 |      Make a new :class:`pandas.MultiIndex` with the passed list of codes deleted.
 |
 |      Parameters
 |      ----------
 |      codes : array-like
 |          Must be a list of tuples when ``level`` is not specified.
 |      level : int or level name, default None
 |      errors : str, default 'raise'
 |
 |      Returns
 |      -------
 |      MultiIndex
 |
 |      Examples
 |      --------
 |      >>> idx = pd.MultiIndex.from_product([(0, 1, 2), ('green', 'purple')],
 |      ...                                  names=["number", "color"])
 |      >>> idx
 |      MultiIndex([(0,  'green'),
 |                  (0, 'purple'),
 |                  (1,  'green'),
 |                  (1, 'purple'),
 |                  (2,  'green'),
 |                  (2, 'purple')],
 |                 names=['number', 'color'])
 |      >>> idx.drop([(1, 'green'), (2, 'purple')])
 |      MultiIndex([(0,  'green'),
 |                  (0, 'purple'),
 |                  (1, 'purple'),
 |                  (2,  'green')],
 |                 names=['number', 'color'])
 |
 |      We can also drop from a specific level.
 |
 |      >>> idx.drop('green', level='color')
 |      MultiIndex([(0, 'purple'),
 |                  (1, 'purple'),
 |                  (2, 'purple')],
 |                 names=['number', 'color'])
 |
 |      >>> idx.drop([1, 2], level=0)
 |      MultiIndex([(0,  'green'),
 |                  (0, 'purple')],
 |                 names=['number', 'color'])
 |
 |  dropna(self, how: AnyAll = 'any') -> MultiIndex
 |      Return Index without NA/NaN values.
 |
 |      Parameters
 |      ----------
 |      how : {'any', 'all'}, default 'any'
 |          If the Index is a MultiIndex, drop the value when any or all levels
 |          are NaN.
 |
 |      Returns
 |      -------
 |      Index
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index([1, np.nan, 3])
 |      >>> idx.dropna()
 |      Index([1.0, 3.0], dtype='float64')
 |
 |  duplicated(self, keep: DropKeep = 'first') -> npt.NDArray[np.bool_]
 |      Indicate duplicate index values.
 |
 |      Duplicated values are indicated as ``True`` values in the resulting
 |      array. Either all duplicates, all except the first, or all except the
 |      last occurrence of duplicates can be indicated.
 |
 |      Parameters
 |      ----------
 |      keep : {'first', 'last', False}, default 'first'
 |          The value or values in a set of duplicates to mark as missing.
 |
 |          - 'first' : Mark duplicates as ``True`` except for the first
 |            occurrence.
 |          - 'last' : Mark duplicates as ``True`` except for the last
 |            occurrence.
 |          - ``False`` : Mark all duplicates as ``True``.
 |
 |      Returns
 |      -------
 |      np.ndarray[bool]
 |
 |      See Also
 |      --------
 |      Series.duplicated : Equivalent method on pandas.Series.
 |      DataFrame.duplicated : Equivalent method on pandas.DataFrame.
 |      Index.drop_duplicates : Remove duplicate values from Index.
 |
 |      Examples
 |      --------
 |      By default, for each set of duplicated values, the first occurrence is
 |      set to False and all others to True:
 |
 |      >>> idx = pd.Index(['lama', 'cow', 'lama', 'beetle', 'lama'])
 |      >>> idx.duplicated()
 |      array([False, False,  True, False,  True])
 |
 |      which is equivalent to
 |
 |      >>> idx.duplicated(keep='first')
 |      array([False, False,  True, False,  True])
 |
 |      By using 'last', the last occurrence of each set of duplicated values
 |      is set on False and all others on True:
 |
 |      >>> idx.duplicated(keep='last')
 |      array([ True, False,  True, False, False])
 |
 |      By setting keep on ``False``, all duplicates are True:
 |
 |      >>> idx.duplicated(keep=False)
 |      array([ True, False,  True, False,  True])
 |
 |  equal_levels(self, other: MultiIndex) -> bool
 |      Return True if the levels of both MultiIndex objects are the same
 |
 |  equals(self, other: object) -> bool
 |      Determines if two MultiIndex objects have the same labeling information
 |      (the levels themselves do not necessarily have to be the same)
 |
 |      See Also
 |      --------
 |      equal_levels
 |
 |  fillna(self, value=None, downcast=None)
 |      fillna is not implemented for MultiIndex
 |
 |  format(
 |      self,
 |      name: bool | None = None,
 |      formatter: Callable | None = None,
 |      na_rep: str | None = None,
 |      names: bool = False,
 |      space: int = 2,
 |      sparsify=None,
 |      adjoin: bool = True
 |  ) -> list
 |      Render a string representation of the Index.
 |
 |  get_level_values(self, level) -> Index
 |      Return vector of label values for requested level.
 |
 |      Length of returned vector is equal to the length of the index.
 |
 |      Parameters
 |      ----------
 |      level : int or str
 |          ``level`` is either the integer position of the level in the
 |          MultiIndex, or the name of the level.
 |
 |      Returns
 |      -------
 |      Index
 |          Values is a level of this MultiIndex converted to
 |          a single :class:`Index` (or subclass thereof).
 |
 |      Notes
 |      -----
 |      If the level contains missing values, the result may be casted to
 |      ``float`` with missing values specified as ``NaN``. This is because
 |      the level is converted to a regular ``Index``.
 |
 |      Examples
 |      --------
 |      Create a MultiIndex:
 |
 |      >>> mi = pd.MultiIndex.from_arrays((list('abc'), list('def')))
 |      >>> mi.names = ['level_1', 'level_2']
 |
 |      Get level values by supplying level as either integer or name:
 |
 |      >>> mi.get_level_values(0)
 |      Index(['a', 'b', 'c'], dtype='object', name='level_1')
 |      >>> mi.get_level_values('level_2')
 |      Index(['d', 'e', 'f'], dtype='object', name='level_2')
 |
 |      If a level contains missing values, the return type of the level
 |      may be cast to ``float``.
 |
 |      >>> pd.MultiIndex.from_arrays([[1, None, 2], [3, 4, 5]]).dtypes
 |      level_0    int64
 |      level_1    int64
 |      dtype: object
 |      >>> pd.MultiIndex.from_arrays([[1, None, 2], [3, 4, 5]]).get_level_values(0)
 |      Index([1.0, nan, 2.0], dtype='float64')
 |
 |  get_loc(self, key)
 |      Get location for a label or a tuple of labels.
 |
 |      The location is returned as an integer/slice or boolean
 |      mask.
 |
 |      Parameters
 |      ----------
 |      key : label or tuple of labels (one for each level)
 |
 |      Returns
 |      -------
 |      int, slice object or boolean mask
 |          If the key is past the lexsort depth, the return may be a
 |          boolean mask array, otherwise it is always a slice or int.
 |
 |      See Also
 |      --------
 |      Index.get_loc : The get_loc method for (single-level) index.
 |      MultiIndex.slice_locs : Get slice location given start label(s) and
 |                              end label(s).
 |      MultiIndex.get_locs : Get location for a label/slice/list/mask or a
 |                            sequence of such.
 |
 |      Notes
 |      -----
 |      The key cannot be a slice, list of same-level labels, a boolean mask,
 |      or a sequence of such. If you want to use those, use
 |      :meth:`MultiIndex.get_locs` instead.
 |
 |      Examples
 |      --------
 |      >>> mi = pd.MultiIndex.from_arrays([list('abb'), list('def')])
 |
 |      >>> mi.get_loc('b')
 |      slice(1, 3, None)
 |
 |      >>> mi.get_loc(('b', 'e'))
 |      1
 |
 |  get_loc_level(self, key, level: IndexLabel = 0, drop_level: bool = True)
 |      Get location and sliced index for requested label(s)/level(s).
 |
 |      Parameters
 |      ----------
 |      key : label or sequence of labels
 |      level : int/level name or list thereof, optional
 |      drop_level : bool, default True
 |          If ``False``, the resulting index will not drop any level.
 |
 |      Returns
 |      -------
 |      tuple
 |          A 2-tuple where the elements :
 |
 |          Element 0: int, slice object or boolean array.
 |
 |          Element 1: The resulting sliced multiindex/index. If the key
 |          contains all levels, this will be ``None``.
 |
 |      See Also
 |      --------
 |      MultiIndex.get_loc  : Get location for a label or a tuple of labels.
 |      MultiIndex.get_locs : Get location for a label/slice/list/mask or a
 |                            sequence of such.
 |
 |      Examples
 |      --------
 |      >>> mi = pd.MultiIndex.from_arrays([list('abb'), list('def')],
 |      ...                                names=['A', 'B'])
 |
 |      >>> mi.get_loc_level('b')
 |      (slice(1, 3, None), Index(['e', 'f'], dtype='object', name='B'))
 |
 |      >>> mi.get_loc_level('e', level='B')
 |      (array([False,  True, False]), Index(['b'], dtype='object', name='A'))
 |
 |      >>> mi.get_loc_level(['b', 'e'])
 |      (1, None)
 |
 |  get_locs(self, seq) -> npt.NDArray[np.intp]
 |      Get location for a sequence of labels.
 |
 |      Parameters
 |      ----------
 |      seq : label, slice, list, mask or a sequence of such
 |         You should use one of the above for each level.
 |         If a level should not be used, set it to ``slice(None)``.
 |
 |      Returns
 |      -------
 |      numpy.ndarray
 |          NumPy array of integers suitable for passing to iloc.
 |
 |      See Also
 |      --------
 |      MultiIndex.get_loc : Get location for a label or a tuple of labels.
 |      MultiIndex.slice_locs : Get slice location given start label(s) and
 |                              end label(s).
 |
 |      Examples
 |      --------
 |      >>> mi = pd.MultiIndex.from_arrays([list('abb'), list('def')])
 |
 |      >>> mi.get_locs('b')  # doctest: +SKIP
 |      array([1, 2], dtype=int64)
 |

In [40]:
help(pd.MultiIndex.from_arrays)

Help on method from_arrays in module pandas.core.indexes.multi:

from_arrays(
    arrays,
    sortorder: int | None = None,
    names: Sequence[Hashable] | Hashable | lib.NoDefault = <no_default>
) -> MultiIndex class method of pandas.core.indexes.multi.MultiIndex
    Convert arrays to MultiIndex.

    Parameters
    ----------
    arrays : list / sequence of array-likes
        Each array-like gives one level's value for each data point.
        len(arrays) is the number of levels.
    sortorder : int or None
        Level of sortedness (must be lexicographically sorted by that
        level).
    names : list / sequence of str, optional
        Names for the levels in the index.

    Returns
    -------
    MultiIndex

    See Also
    --------
    MultiIndex.from_tuples : Convert list of tuples to MultiIndex.
    MultiIndex.from_product : Make a MultiIndex from cartesian product
                              of iterables.
    MultiIndex.from_frame : Make a MultiIndex from a DataFrame.

    Examples
    --------
    >>> arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]
    >>> pd.MultiIndex.from_arrays(arrays, names=('number', 'color'))
    MultiIndex([(1,  'red'),
                (1, 'blue'),
                (2,  'red'),
                (2, 'blue')],
               names=['number', 'color'])

In [49]:
# Sample sales data
data = {
    'Date': ['2022-01-01', '2022-01-01', '2022-01-02', '2022-01-02', '2022-01-03'],
    'Product': ['A', 'B', 'A', 'B', 'A'],
    'Region': ['North', 'South', 'North', 'South', 'North'],
    'Sales': [100, 150, 120, 80, 200],
    'Quantity': [2, 3, 1, 2, 4]
}

sales_df = pd.DataFrame(data)

# Convert 'Date' column to datetime type
sales_df['Date'] = pd.to_datetime(sales_df['Date'])

# Display the DataFrame
print("Sales DataFrame:")
print(sales_df)

Sales DataFrame:
        Date Product Region  Sales  Quantity
0 2022-01-01       A  North    100         2
1 2022-01-01       B  South    150         3
2 2022-01-02       A  North    120         1
3 2022-01-02       B  South     80         2
4 2022-01-03       A  North    200         4

In [42]:
sales_df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
# manually set an index
# must save it in a variable!!! (inplace param OR new variable)

sales_df.set_index(['Date'], inplace=True)

# 'date' index column is separated(lower)

In [47]:
sales_df

           Product Region  Sales  Quantity
Date
2022-01-01       A  North    100         2
2022-01-01       B  South    150         3
2022-01-02       A  North    120         1
2022-01-02       B  South     80         2
2022-01-03       A  North    200         4

In [50]:
# using original data input cell

mindex_df = sales_df.set_index(['Date', 'Region'])

mindex_df

                  Product  Sales  Quantity
Date       Region
2022-01-01 North        A    100         2
           South        B    150         3
2022-01-02 North        A    120         1
           South        B     80         2
2022-01-03 North        A    200         4

In [51]:
mindex_df['Product']

Date        Region
2022-01-01  North     A
            South     B
2022-01-02  North     A
            South     B
2022-01-03  North     A
Name: Product, dtype: object

In [ ]:
# selecting multiple columns (use double square brackets)

mindex_df[['Product','Quantity']]

                  Product  Quantity
Date       Region
2022-01-01 North        A         2
           South        B         3
2022-01-02 North        A         1
           South        B         2
2022-01-03 North        A         4

In [53]:
# df.loc[row_label, column_label]

mindex_df.loc[:,'Product':'Quantity']

                  Product  Sales  Quantity
Date       Region
2022-01-01 North        A    100         2
           South        B    150         3
2022-01-02 North        A    120         1
           South        B     80         2
2022-01-03 North        A    200         4

In [54]:
# using row labels, since that's where we have the multi-index

mindex_df.loc['2022-01-01',:]

       Product  Sales  Quantity
Region
North        A    100         2
South        B    150         3

In [ ]:
# slicing by the subsequent levels of indices e.g. by region

mindex_df.loc[(),:] # paren indicates there are multiple levels
mindex_df.loc[(slice(None)),:] # None
mindex_df.loc[(slice(None)),'South'] # for the south region

In [ ]:
mindex_df.loc[(slice(None)),'South',:] # ignore date, and slice by 'south'

           Product  Sales  Quantity
Date
2022-01-01       B    150         3
2022-01-02       B     80         2

In [57]:
sales_df

        Date Product Region  Sales  Quantity
0 2022-01-01       A  North    100         2
1 2022-01-01       B  South    150         3
2 2022-01-02       A  North    120         1
3 2022-01-02       B  South     80         2
4 2022-01-03       A  North    200         4

In [63]:
three_level_df = sales_df.set_index(['Date','Product','Region'])

three_level_df

                           Sales  Quantity
Date       Product Region
2022-01-01 A       North     100         2
           B       South     150         3
2022-01-02 A       North     120         1
           B       South      80         2
2022-01-03 A       North     200         4

In [62]:
three_level_df.loc[(slice(None), slice(None), slice(None)),:]

                           Sales  Quantity
Date       Product Region
2022-01-01 A       North     100         2
           B       South     150         3
2022-01-02 A       North     120         1
           B       South      80         2
2022-01-03 A       North     200         4

In [64]:
three_level_df.loc[(slice(None), 'B', slice(None)),:]

                           Sales  Quantity
Date       Product Region
2022-01-01 B       South     150         3
2022-01-02 B       South      80         2

In [65]:
three_level_df.loc[(slice(None), slice(None), 'North'),:]

                           Sales  Quantity
Date       Product Region
2022-01-01 A       North     100         2
2022-01-02 A       North     120         1
2022-01-03 A       North     200         4

In [66]:
# unstack

mindex_df

                  Product  Sales  Quantity
Date       Region
2022-01-01 North        A    100         2
           South        B    150         3
2022-01-02 North        A    120         1
           South        B     80         2
2022-01-03 North        A    200         4

In [70]:
unstack_df = mindex_df.unstack()

unstack_df

# first level of row indices kept, others are unstacked as columns

           Product        Sales        Quantity
Region       North South  North  South    North South
Date
2022-01-01       A     B  100.0  150.0      2.0   3.0
2022-01-02       A     B  120.0   80.0      1.0   2.0
2022-01-03       A   NaN  200.0    NaN      4.0   NaN

In [71]:
unstack_df.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03'], dtype='datetime64[ns]', name='Date', freq=None)

In [72]:
unstack_df.columns

MultiIndex([( 'Product', 'North'),
            ( 'Product', 'South'),
            (   'Sales', 'North'),
            (   'Sales', 'South'),
            ('Quantity', 'North'),
            ('Quantity', 'South')],
           names=[None, 'Region'])

In [73]:
unstack_df[['Product','Sales']]

           Product        Sales
Region       North South  North  South
Date
2022-01-01       A     B  100.0  150.0
2022-01-02       A     B  120.0   80.0
2022-01-03       A   NaN  200.0    NaN

In [74]:
unstack_df.loc[:,(slice(None), slice(None))]

           Product        Sales        Quantity
Region       North South  North  South    North South
Date
2022-01-01       A     B  100.0  150.0      2.0   3.0
2022-01-02       A     B  120.0   80.0      1.0   2.0
2022-01-03       A   NaN  200.0    NaN      4.0   NaN

In [75]:
unstack_df.loc[:,(slice(None), 'South')]

           Product  Sales Quantity
Region       South  South    South
Date
2022-01-01       B  150.0      3.0
2022-01-02       B   80.0      2.0
2022-01-03     NaN    NaN      NaN