In [2]:
import pandas as pd

In [3]:
data = pd.read_csv(r"D:\2-zindua\03-python-data-analysis\zindua-python-data-analysis\wk2_pandas\QVI_purchase_behaviour (1).csv")

In [4]:
df = pd.read_excel(r"D:\2-zindua\03-python-data-analysis\zindua-python-data-analysis\wk2_pandas\QVI_transaction_data (2).xlsx")

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72637 entries, 0 to 72636
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LYLTY_CARD_NBR    72637 non-null  int64
 1   LIFESTAGE         72637 non-null  object
 2   PREMIUM_CUSTOMER  72637 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.7+ MB

In [6]:
data.head()

   LYLTY_CARD_NBR               LIFESTAGE PREMIUM_CUSTOMER
0            1000   YOUNG SINGLES/COUPLES          Premium
1            1002   YOUNG SINGLES/COUPLES       Mainstream
2            1003          YOUNG FAMILIES           Budget
3            1004   OLDER SINGLES/COUPLES       Mainstream
4            1005  MIDAGE SINGLES/COUPLES       Mainstream

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DATE            264836 non-null  int64
 1   STORE_NBR       264836 non-null  int64
 2   LYLTY_CARD_NBR  264836 non-null  int64
 3   TXN_ID          264836 non-null  int64
 4   PROD_NBR        264836 non-null  int64
 5   PROD_NAME       264836 non-null  object
 6   PROD_QTY        264836 non-null  int64
 7   TOT_SALES       264836 non-null  float64
dtypes: float64(1), int64(6), object(1)
memory usage: 16.2+ MB

In [8]:
full_df = data.merge(df, how='left',on='LYLTY_CARD_NBR')

In [10]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   LYLTY_CARD_NBR    264836 non-null  int64
 1   LIFESTAGE         264836 non-null  object
 2   PREMIUM_CUSTOMER  264836 non-null  object
 3   DATE              264836 non-null  int64
 4   STORE_NBR         264836 non-null  int64
 5   TXN_ID            264836 non-null  int64
 6   PROD_NBR          264836 non-null  int64
 7   PROD_NAME         264836 non-null  object
 8   PROD_QTY          264836 non-null  int64
 9   TOT_SALES         264836 non-null  float64
dtypes: float64(1), int64(6), object(3)
memory usage: 20.2+ MB

In [9]:
full_df.head()

,LYLTY_CARD_NBR,LIFESTAGE,PREMIUM_CUSTOMER,DATE,STORE_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,1000,YOUNG SINGLES/COUPLES,Premium,43390,1,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,1002,YOUNG SINGLES/COUPLES,Mainstream,43359,1,2,58,Red Rock Deli Chikn&Garlic Aioli 150g,1,2.7
2,1003,YOUNG FAMILIES,Budget,43531,1,3,52,Grain Waves Sour Cream&Chives 210G,1,3.6
3,1003,YOUNG FAMILIES,Budget,43532,1,4,106,Natural ChipCo Hony Soy Chckn175g,1,3.0
4,1004,OLDER SINGLES/COUPLES,Mainstream,43406,1,5,96,WW Original Stacked Chips 160g,1,1.9

## Questions we could ask
Univariate -> bivariate -> multivariate (global view/summary stats)
### Univariate
- How big is the customer base?
- Total sales
- How many unique products are there?
- What is the date range of my dataset?
- How many transactions?
- Total quantity sold
- Distributions:
    - How many customers by lifestage(), individual life stage()
    - Sales: median sale, outliers
    - premium customer by lifestage

# Group by & Pivot tables
## Group by
- always group by sth categorical, repetitive
- computation on a numerical field against a categorical field
- i.e. `pd.groupby(")[aggregate_numerical]`

In [12]:
full_df.columns

Index(['LYLTY_CARD_NBR', 'LIFESTAGE', 'PREMIUM_CUSTOMER', 'DATE', 'STORE_NBR',
       'TXN_ID', 'PROD_NBR', 'PROD_NAME', 'PROD_QTY', 'TOT_SALES'],
      dtype='object')

In [13]:
# sales per lifestage
# is it repetitive?

full_df.groupby(['LIFESTAGE'])

In [15]:
full_df.shape

(264836, 10)

In [ ]:
full_df['LIFESTAGE'].nunique()      # 7 != 264836

7

In [20]:
full_df['LIFESTAGE'].unique()

array(['YOUNG SINGLES/COUPLES', 'YOUNG FAMILIES', 'OLDER SINGLES/COUPLES',
       'MIDAGE SINGLES/COUPLES', 'NEW FAMILIES', 'OLDER FAMILIES',
       'RETIREES'], dtype=object)

In [14]:
full_df.groupby('LIFESTAGE')['TOT_SALES'].sum()

LIFESTAGE
MIDAGE SINGLES/COUPLES    184751.30
NEW FAMILIES               50433.45
OLDER FAMILIES            353767.20
OLDER SINGLES/COUPLES     402426.75
RETIREES                  366470.90
YOUNG FAMILIES            316160.10
YOUNG SINGLES/COUPLES     260405.30
Name: TOT_SALES, dtype: float64

In [16]:
full_df.groupby('LIFESTAGE')[['TOT_SALES']].sum()

                        TOT_SALES
LIFESTAGE
MIDAGE SINGLES/COUPLES  184751.30
NEW FAMILIES             50433.45
OLDER FAMILIES          353767.20
OLDER SINGLES/COUPLES   402426.75
RETIREES                366470.90
YOUNG FAMILIES          316160.10
YOUNG SINGLES/COUPLES   260405.30

In [18]:
full_df.groupby('LIFESTAGE')[['TOT_SALES']].sum().sort_values(by='TOT_SALES')

                        TOT_SALES
LIFESTAGE
NEW FAMILIES             50433.45
MIDAGE SINGLES/COUPLES  184751.30
YOUNG SINGLES/COUPLES   260405.30
YOUNG FAMILIES          316160.10
OLDER FAMILIES          353767.20
RETIREES                366470.90
OLDER SINGLES/COUPLES   402426.75

In [19]:
full_df.groupby('LIFESTAGE')[['TOT_SALES']].sum().sort_values(by='TOT_SALES', ascending=False)

                        TOT_SALES
LIFESTAGE
OLDER SINGLES/COUPLES   402426.75
RETIREES                366470.90
OLDER FAMILIES          353767.20
YOUNG FAMILIES          316160.10
YOUNG SINGLES/COUPLES   260405.30
MIDAGE SINGLES/COUPLES  184751.30
NEW FAMILIES             50433.45

In [ ]:
full_df.groupby(['LIFESTAGE', 'PREMIUM_CUSTOMER'])[['TOT_SALES']].mean()    # order matters

                                         TOT_SALES
LIFESTAGE              PREMIUM_CUSTOMER
MIDAGE SINGLES/COUPLES Budget             7.074661
                       Mainstream         7.647284
                       Premium            7.112056
NEW FAMILIES           Budget             7.297321
                       Mainstream         7.317806
                       Premium            7.231655
OLDER FAMILIES         Budget             7.269570
                       Mainstream         7.262395
                       Premium            7.322945
OLDER SINGLES/COUPLES  Budget             7.430315
                       Mainstream         7.282116
                       Premium            7.449766
RETIREES               Budget             7.443445
                       Mainstream         7.252262
                       Premium            7.456174
YOUNG FAMILIES         Budget             7.287201
                       Mainstream         7.189025
                       Premium            7.266756
YOUNG SINGLES/COUPLES  Budget             6.615624
                       Mainstream         7.558339
                       Premium            6.629852

In [23]:
full_df.groupby(['LIFESTAGE', 'PREMIUM_CUSTOMER'])[['TOT_SALES', 'PROD_QTY']].mean()

                                         TOT_SALES  PROD_QTY
LIFESTAGE              PREMIUM_CUSTOMER
MIDAGE SINGLES/COUPLES Budget             7.074661  1.891633
                       Mainstream         7.647284  1.911656
                       Premium            7.112056  1.889727
NEW FAMILIES           Budget             7.297321  1.853910
                       Mainstream         7.317806  1.857634
                       Premium            7.231655  1.860919
OLDER FAMILIES         Budget             7.269570  1.945812
                       Mainstream         7.262395  1.948610
                       Premium            7.322945  1.980969
OLDER SINGLES/COUPLES  Budget             7.430315  1.913403
                       Mainstream         7.282116  1.910525
                       Premium            7.449766  1.914273
RETIREES               Budget             7.443445  1.892244
                       Mainstream         7.252262  1.887543
                       Premium            7.456174  1.900122
YOUNG FAMILIES         Budget             7.287201  1.940749
                       Mainstream         7.189025  1.940342
                       Premium            7.266756  1.937732
YOUNG SINGLES/COUPLES  Budget             6.615624  1.803830
                       Mainstream         7.558339  1.852498
                       Premium            6.629852  1.804012

In [24]:
full_df.groupby(['LIFESTAGE']).agg({'TOT_SALES':'sum',
                                    'PROD_QTY':'mean'})

                        TOT_SALES  PROD_QTY
LIFESTAGE
MIDAGE SINGLES/COUPLES  184751.30  1.900478
NEW FAMILIES             50433.45  1.856771
OLDER FAMILIES          353767.20  1.954729
OLDER SINGLES/COUPLES   402426.75  1.912719
RETIREES                366470.90  1.892289
YOUNG FAMILIES          316160.10  1.939828
YOUNG SINGLES/COUPLES   260405.30  1.831762

In [26]:
full_df.groupby(['LIFESTAGE']).agg(
    total_sales = ('TOT_SALES','sum'),
    average_sales = ('TOT_SALES','mean')
)

                        total_sales  average_sales
LIFESTAGE
MIDAGE SINGLES/COUPLES    184751.30       7.357678
NEW FAMILIES               50433.45       7.289124
OLDER FAMILIES            353767.20       7.279760
OLDER SINGLES/COUPLES     402426.75       7.386823
RETIREES                  366470.90       7.364325
YOUNG FAMILIES            316160.10       7.252709
YOUNG SINGLES/COUPLES     260405.30       7.158515

## Pivot tables

In [27]:
pd.pivot_table(full_df, values=['TOT_SALES','PROD_QTY'], index='LIFESTAGE',columns='PREMIUM_CUSTOMER', aggfunc='mean')

                        PROD_QTY                      TOT_SALES             \
PREMIUM_CUSTOMER          Budget Mainstream   Premium    Budget Mainstream
LIFESTAGE
MIDAGE SINGLES/COUPLES  1.891633   1.911656  1.889727  7.074661   7.647284
NEW FAMILIES            1.853910   1.857634  1.860919  7.297321   7.317806
OLDER FAMILIES          1.945812   1.948610  1.980969  7.269570   7.262395
OLDER SINGLES/COUPLES   1.913403   1.910525  1.914273  7.430315   7.282116
RETIREES                1.892244   1.887543  1.900122  7.443445   7.252262
YOUNG FAMILIES          1.940749   1.940342  1.937732  7.287201   7.189025
YOUNG SINGLES/COUPLES   1.803830   1.852498  1.804012  6.615624   7.558339


PREMIUM_CUSTOMER         Premium
LIFESTAGE
MIDAGE SINGLES/COUPLES  7.112056
NEW FAMILIES            7.231655
OLDER FAMILIES          7.322945
OLDER SINGLES/COUPLES   7.449766
RETIREES                7.456174
YOUNG FAMILIES          7.266756
YOUNG SINGLES/COUPLES   6.629852